version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./content:/usr/share/nginx/content
    depends_on:
      - app
  
  app:
    build: app
    volumes:
      - ./content:/content
    ports:
      - '5000:5000'
