version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: m0kr4n3/projet_2cs_cdn:nginx
    ports:
      # - "443:443"
      # - "80:80"
      - "8000:8000"
    volumes:
      - ./content:/usr/share/nginx/content/
    depends_on:
      - app-service
  
  app-service:
    build:
      context: .
      dockerfile: app.Dockerfile
    image: m0kr4n3/projet_2cs_cdn:app
    ports:
      - '5000:5000'
    volumes:
      - ./content:/content


