version: '3'

services:
  varnish:
    build: varnish
    ports:
      - "8080:8080"
  nginx:
    image: nginx:1.25.0
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl